development:
  sessions:
    default:
      database: lo_dev
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: false

test:
  sessions:
    default:
      database: lo_test
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true

production:
  sessions:
    default:
      database: lo_production
      # heroku
      # uri: <%= ENV['MONGOHQ_URL'] %>
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true
